version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: wonderpay
      POSTGRES_USER: wpay
      POSTGRES_PASSWORD: wpay
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "senha"
    ports: 
      - "9090:80"
    depends_on: 
      - postgres